// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldExplorerEurope.API.Data;

namespace WorldExplorerEurope.API.Migrations
{
    [DbContext(typeof(WorldExplorerContext))]
    [Migration("20200531142320_AddData")]
    partial class AddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEUMember")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("476bc0eb-e17d-4967-b86f-1e09682c81b5"),
                            Capital = "Mariehamn",
                            Currency = "Euro",
                            Description = "The Åland Islands or Åland is an archipelago province at the entrance to the Gulf of Bothnia in the Baltic Sea belonging to Finland. It is autonomous, demilitarised and is the only monolingually Swedish-speaking region in Finland. It is the smallest region of Finland, constituting 0.51% of its land area and 0.54% of its population.",
                            Flag = "https://restcountries.eu/data/ala.svg",
                            IsEUMember = true,
                            Name = "Åland Islands",
                            Population = 28875L
                        },
                        new
                        {
                            Id = new Guid("7d4ceeaa-d15d-4775-9227-627be6acbd00"),
                            Capital = "Tirana",
                            Currency = "Albanian lek",
                            Description = "Albania, officially the Republic of Albania, is a country in Southeast Europe on the Adriatic and Ionian Sea within the Mediterranean Sea. It shares land borders with Montenegro to the northwest, Kosovo to the northeast, North Macedonia to the east, Greece to the south and maritime borders with Greece, Montenegro and Italy to the west.",
                            Flag = "https://restcountries.eu/data/alb.svg",
                            IsEUMember = true,
                            Name = "Albania",
                            Population = 2886026L
                        },
                        new
                        {
                            Id = new Guid("023af9af-a306-4870-a7b7-70f5d331a66b"),
                            Capital = "Andorra la Vella",
                            Currency = "Euro",
                            Description = "Andorra, officially the Principality of Andorra, also called the Principality of the Valleys of Andorra, is a sovereign landlocked microstate on the Iberian Peninsula, in the eastern Pyrenees, bordered by France to the north and Spain to the south. Believed to have been created by Charlemagne, Andorra was ruled by the count of Urgell until 988, when it was transferred to the Roman Catholic Diocese of Urgell. The present principality was formed by a charter in 1278. It is known as a principality as it is a diarchy headed by two princes: the Catholic bishop of Urgell in Catalonia, Spain, and the president of the French Republic.",
                            Flag = "https://restcountries.eu/data/and.svg",
                            IsEUMember = true,
                            Name = "Andorra",
                            Population = 78014L
                        },
                        new
                        {
                            Id = new Guid("6ff85e22-61d5-4ba5-a805-276358c3dff9"),
                            Capital = "Vienna",
                            Currency = "Euro",
                            Description = "Austria, officially the Republic of Austria, is a landlocked East Alpine country in the southern part of Central Europe. It is composed of nine federated states (Bundesländer), one of which is Vienna, Austria's capital and its largest city. It is bordered by Germany to the northwest, Czech Republic to the north, Slovakia to the northeast, Hungary to the east, Slovenia and Italy to the south, and Switzerland and Liechtenstein to the west. Austria occupies an area of 83,879 km2 (32,386 sq mi) and has a population of nearly 9 million people. While German is the country's official language, many Austrians communicate informally in a variety of Bavarian dialects.",
                            Flag = "https://restcountries.eu/data/aut.svg",
                            IsEUMember = true,
                            Name = "Austria",
                            Population = 8725931L
                        },
                        new
                        {
                            Id = new Guid("8576e077-183f-4e29-8a6d-5e5a49a021c0"),
                            Capital = "Minsk",
                            Currency = "New Belarusian ruble",
                            Description = "Belarus, officially the Republic of Belarus, formerly known by its Russian name Byelorussia or Belorussia, is a landlocked country in Eastern Europe bordered by Russia to the northeast, Ukraine to the south, Poland to the west, and Lithuania and Latvia to the northwest. Its capital and most populous city is Minsk. Over 40% of its 207,600 square kilometres (80,200 sq mi) is forested. Its major economic sectors are service industries and manufacturing. Until the 20th century, different states at various times controlled the lands of modern-day Belarus, including the Principality of Polotsk, the Grand Duchy of Lithuania, the Polish–Lithuanian Commonwealth, and the Russian Empire.",
                            Flag = "https://restcountries.eu/data/blr.svg",
                            IsEUMember = true,
                            Name = "Belarus",
                            Population = 9498700L
                        },
                        new
                        {
                            Id = new Guid("4963724f-4004-44e7-98dd-3e102042eb62"),
                            Capital = "Brussels",
                            Currency = "Euro",
                            Description = "Belgium, officially the Kingdom of Belgium, is a country in Western Europe. It is bordered by the Netherlands to the north, Germany to the east, Luxembourg to the southeast, France to the southwest, and the North Sea to the northwest. It covers an area of 30,689 km2 (11,849 sq mi) and has a population of more than 11.5 million, making it the 22nd most densely populated country in the world and the 6th most densely populated country in Europe, with a density of 376 per square kilometre (970/sq mi). The capital and largest city is Brussels; other major cities are Antwerp, Ghent, Charleroi and Liège.",
                            Flag = "https://restcountries.eu/data/bel.svg",
                            IsEUMember = true,
                            Name = "Belgium",
                            Population = 11319511L
                        },
                        new
                        {
                            Id = new Guid("00fed494-1514-40d1-a8a0-3772e3d8824d"),
                            Capital = "Sarajevo",
                            Currency = "Bosnia and Herzegovina convertible mark",
                            Description = "Bosnia and Herzegovina, abbreviated BiH or B&H, sometimes called Bosnia–Herzegovina and often known informally as Bosnia, is a country of South and Southeast Europe, located within the Balkans. Sarajevo is the capital and largest city.",
                            Flag = "https://restcountries.eu/data/bih.svg",
                            IsEUMember = true,
                            Name = "Bosnia and Herzegovina",
                            Population = 3531159L
                        },
                        new
                        {
                            Id = new Guid("f9266fa7-d009-44c1-bc84-bef8e948caa2"),
                            Capital = "Sofia",
                            Currency = "Bulgarian lev",
                            Description = "Bulgaria, officially the Republic of Bulgaria, is a country in Southeast Europe. It is bordered by Romania to the north, Serbia and North Macedonia to the west, Greece and Turkey to the south, and the Black Sea to the east. The capital and largest city is Sofia; other major cities are Plovdiv, Varna and Burgas. With a territory of 110,994 square kilometres (42,855 sq mi), Bulgaria is Europe's 16th-largest country.",
                            Flag = "https://restcountries.eu/data/bgr.svg",
                            IsEUMember = true,
                            Name = "Bulgaria",
                            Population = 7153784L
                        },
                        new
                        {
                            Id = new Guid("691703c7-9a52-42fe-a87f-5e7115e28f30"),
                            Capital = "Zagreb",
                            Currency = "Croatian kuna",
                            Description = "Croatia, officially the Republic of Croatia, is a country in Southeast Europe. It borders Slovenia to the northwest, Hungary to the northeast, Serbia to the east, Bosnia and Herzegovina, and Montenegro to the southeast, sharing a maritime border with Italy. Its capital, Zagreb, forms one of the country's primary subdivisions, along with twenty counties. Croatia has an area of 56,594 square kilometres and a population of 4.28 million, most of whom are Roman Catholics.",
                            Flag = "https://restcountries.eu/data/hrv.svg",
                            IsEUMember = true,
                            Name = "Croatia",
                            Population = 4190669L
                        },
                        new
                        {
                            Id = new Guid("da3b2494-96a0-4003-81a2-81e434524285"),
                            Capital = "Nicosia",
                            Currency = "Euro",
                            Description = "Cyprus, officially the Republic of Cyprus, is an island country in the Eastern Mediterranean and the third-largest and third-most populous island in the Mediterranean, located south of Turkey, west of Syria and Lebanon, north of Israel, the Gaza Strip and Egypt, and southeast of Greece.",
                            Flag = "https://restcountries.eu/data/cyp.svg",
                            IsEUMember = true,
                            Name = "Cyprus",
                            Population = 847000L
                        },
                        new
                        {
                            Id = new Guid("bb6f1d45-0219-45c5-bb30-34dd9b0b341f"),
                            Capital = "Prague",
                            Currency = "Czech koruna",
                            Description = "The Czech Republic, also known by its short-form name, Czechia, is a landlocked country in Central Europe bordered by Poland to the northeast, Slovakia to the southeast, Austria to the south, and Germany to the west. The Czech Republic has hilly landscape that covers an area of 78,866 square kilometers (30,450 sq mi) with a mostly temperate continental climate and oceanic climate. It is a unitary parliamentary republic, with 10.7 million inhabitants. Its capital and largest city is Prague, with 1.3 million residents; other major cities are Brno, Ostrava, Olomouc and Pilsen.",
                            Flag = "https://restcountries.eu/data/cze.svg",
                            IsEUMember = true,
                            Name = "Czech Republic",
                            Population = 10558524L
                        },
                        new
                        {
                            Id = new Guid("df396ddc-06e1-4794-8ae8-4c6e294a3675"),
                            Capital = "Copenhagen",
                            Currency = "Danish krone",
                            Description = "Denmark, officially the Kingdom of Denmark, is a Nordic country in Northwest Europe. Denmark proper, which is the southernmost of the Scandinavian countries, consists of a peninsula, Jutland, and an archipelago of 443 named islands, with the largest being Zealand, Funen and the North Jutlandic Island. The islands are characterised by flat, arable land and sandy coasts, low elevation and a temperate climate. The southernmost of the Scandinavian nations, Denmark lies southwest of Sweden and south of Norway, and is bordered to the south by Germany. The Kingdom of Denmark also includes two autonomous territories in the North Atlantic Ocean: the Faroe Islands and Greenland. Denmark has a total area of 42,924 km2 (16,573 sq mi), land area of 42,394 km2 (16,368 sq mi), and the total area including Greenland and the Faroe Islands is 2,210,579 km2 (853,509 sq mi), and a population of 5.8 million in Denmark proper.",
                            Flag = "https://restcountries.eu/data/dnk.svg",
                            IsEUMember = true,
                            Name = "Denmark",
                            Population = 5717014L
                        },
                        new
                        {
                            Id = new Guid("e5970e72-bd18-4996-a595-ddc658cd8d53"),
                            Capital = "Tallinn",
                            Currency = "Euro",
                            Description = "Estonia, officially the Republic of Estonia, is a country on the eastern coast of the Baltic Sea in Northern Europe. It is bordered to the north by the Gulf of Finland with Finland on the other side, to the west by the Baltic Sea with Sweden on the other side, to the south by Latvia (343 km), and to the east by Lake Peipus and Russia (338.6 km). The territory of Estonia consists of the mainland and of 2,222 islands in the Baltic Sea, covering a total area of 45,227 km2 (17,462 sq mi), water 2,839 km2 (1,096 sq mi), land area 42,388 km2 (16,366 sq mi), and is influenced by a humid continental climate. The official language of the country, Estonian, is the second-most-spoken Finnic language.",
                            Flag = "https://restcountries.eu/data/est.svg",
                            IsEUMember = true,
                            Name = "Estonia",
                            Population = 1315944L
                        },
                        new
                        {
                            Id = new Guid("9d609d89-8e7a-4218-a71f-9c27180119f1"),
                            Capital = "Tórshavn",
                            Currency = "Danish krone",
                            Description = "The Faroe Islands, , is a North Atlantic archipelago located 320 kilometres (200 mi) north-northwest of Scotland, and about halfway between Norway and Iceland. It is an autonomous territory within the Kingdom of Denmark. The islands have a total area of about 1,400 square kilometres (540 sq mi) with a population of 51,783 as of June 2019.",
                            Flag = "https://restcountries.eu/data/fro.svg",
                            IsEUMember = true,
                            Name = "Faroe Islands",
                            Population = 49376L
                        },
                        new
                        {
                            Id = new Guid("73d00cef-69e3-40ae-b756-df15767e89dd"),
                            Capital = "Helsinki",
                            Currency = "Euro",
                            Description = "Finland, officially the Republic of Finland, is a Nordic country in Northern Europe bordering the Baltic Sea, Gulf of Bothnia, and Gulf of Finland, between Sweden to the west, Russia to the east, Estonia to the south, and north-eastern Norway to the north. The capital and largest city is Helsinki. Other major cities are Espoo, Tampere, Vantaa, Oulu, Turku, Jyväskylä, Lahti and Kuopio.",
                            Flag = "https://restcountries.eu/data/fin.svg",
                            IsEUMember = true,
                            Name = "Finland",
                            Population = 5491817L
                        },
                        new
                        {
                            Id = new Guid("af1fd177-7df3-4dd1-b449-068b0d701459"),
                            Capital = "Paris",
                            Currency = "Euro",
                            Description = "France, officially the French Republic, is a country whose territory consists of metropolitan France in Western Europe and several overseas regions and territories. The metropolitan area of France extends from the Mediterranean Sea to the English Channel and the North Sea, and from the Rhine to the Atlantic Ocean. It is bordered by Belgium, Luxembourg and Germany to the northeast, Switzerland and Italy to the east, and Andorra and Spain to the south. The overseas territories include French Guiana in South America and several islands in the Atlantic, Pacific and Indian oceans. The country's 18 integral regions span a combined area of 643,801 square kilometres (248,573 sq mi) and a total population of 67.02 million. France is a unitary semi-presidential republic with its capital in Paris, the country's largest city and main cultural and commercial centre. Other major urban areas include Lyon, Marseille, Toulouse, Bordeaux, Lille and Nice. France, including its overseas territories, has the most number of time zones of any country, with a total of 12.",
                            Flag = "https://restcountries.eu/data/fra.svg",
                            IsEUMember = true,
                            Name = "France",
                            Population = 66710000L
                        },
                        new
                        {
                            Id = new Guid("37dd0095-5300-499f-a5c8-320cf28142ba"),
                            Capital = "Berlin",
                            Currency = "Euro",
                            Description = "Germany, constitutionally the Federal Republic of Germany, is a country in Central and Western Europe. Covering an area of 357,022 square kilometres (137,847 sq mi), it lies between the Baltic and North seas to the north, and the Alps and Lake Constance to the south. It borders Denmark to the north, Poland and the Czech Republic to the east, Austria and Switzerland to the south, and France, Luxembourg, Belgium, and the Netherlands to the west. With 83 million inhabitants of its 16 constituent states, it is the second-most populous country in Europe after Russia, as well as the most populous member state of the European Union. Its capital and largest city is Berlin, while its largest urban area is the Ruhr. The country's financial capital is Frankfurt; other major cities include Hamburg, Munich, Cologne, and Stuttgart.",
                            Flag = "https://restcountries.eu/data/deu.svg",
                            IsEUMember = true,
                            Name = "Germany",
                            Population = 81770900L
                        },
                        new
                        {
                            Id = new Guid("ed2f71f4-66f7-4597-a631-059a5967b659"),
                            Capital = "Gibraltar",
                            Currency = "Gibraltar pound",
                            Description = "Gibraltar is a British Overseas Territory located at the southern tip of the Iberian Peninsula. It has an area of 6.7 km2 (2.6 sq mi) and is bordered to the north by Spain. The landscape is dominated by the Rock of Gibraltar at the foot of which is a densely populated town area, home to over 32,000 people, primarily Gibraltarians.",
                            Flag = "https://restcountries.eu/data/gib.svg",
                            IsEUMember = true,
                            Name = "Gibraltar",
                            Population = 33140L
                        },
                        new
                        {
                            Id = new Guid("700e77da-10c0-4571-9d41-ad79383f2573"),
                            Capital = "Athens",
                            Currency = "Euro",
                            Description = "Gibraltar is a British Overseas Territory located at the southern tip of the Iberian Peninsula. It has an area of 6.7 km2 (2.6 sq mi) and is bordered to the north by Spain. The landscape is dominated by the Rock of Gibraltar at the foot of which is a densely populated town area, home to over 32,000 people, primarily Gibraltarians.",
                            Flag = "https://restcountries.eu/data/grc.svg",
                            IsEUMember = true,
                            Name = "Greece",
                            Population = 10858018L
                        },
                        new
                        {
                            Id = new Guid("3e3a5cfb-0861-4725-a519-8a55fba11e7c"),
                            Capital = "St. Peter Port",
                            Currency = "British pound",
                            Description = "Guernsey is an island in the English Channel off the coast of Normandy. It lies roughly north of Saint-Malo and to the west of Jersey and the Cotentin Peninsula. With several smaller nearby islands, it forms a jurisdiction within the Bailiwick of Guernsey, a British Crown dependency. The jurisdiction is made up of ten parishes on the island of Guernsey, three other inhabited islands, and many small islets and rocks.",
                            Flag = "https://restcountries.eu/data/ggy.svg",
                            IsEUMember = true,
                            Name = "Guernsey",
                            Population = 62999L
                        },
                        new
                        {
                            Id = new Guid("8ef2dcdf-8665-46de-9f69-a3fcd71bbcc3"),
                            Capital = "Rome",
                            Currency = "Euro",
                            Description = "The Holy See, also called the See of Rome, is the jurisdiction of the Bishop of Rome, known as the pope, which includes the apostolic episcopal see of the Diocese of Rome with universal ecclesiastical jurisdiction of the worldwide Catholic Church, as well as a sovereign entity of international law.",
                            Flag = "https://restcountries.eu/data/vat.svg",
                            IsEUMember = true,
                            Name = "Holy See",
                            Population = 451L
                        },
                        new
                        {
                            Id = new Guid("be40d8c3-b922-4ac5-8d49-27f63b3983cb"),
                            Capital = "Budapest",
                            Currency = "Hungarian forint",
                            Description = "Hungary is a country in Central Europe. Spanning 93,030 square kilometres (35,920 sq mi) in the Carpathian Basin, it borders Slovakia to the north, Ukraine to the northeast, Romania to the east and southeast, Serbia to the south, Croatia and Slovenia to the southwest, and Austria to the west. With about 10 million inhabitants, Hungary is a medium-sized member state of the European Union. The official language is Hungarian, which is the most widely spoken Uralic language in the world, and among the few non-Indo-European languages to be widely spoken in Europe. Hungary's capital and largest city is Budapest; other major urban areas include Debrecen, Szeged, Miskolc, Pécs, and Győr.",
                            Flag = "https://restcountries.eu/data/hun.svg",
                            IsEUMember = true,
                            Name = "Hungary",
                            Population = 9823000L
                        },
                        new
                        {
                            Id = new Guid("7b50048f-c613-4db5-858c-8b2a0ced2027"),
                            Capital = "Reykjavík",
                            Currency = "Icelandic króna",
                            Description = "Iceland is a Nordic island country in the North Atlantic, with a population of 364,260 and an area of 103,000 km2 (40,000 sq mi), making it the most sparsely populated country in Europe. The capital and largest city is Reykjavík. Reykjavik and the surrounding areas in the southwest of the country are home to over two-thirds of the population. Iceland is volcanically and geologically active. The interior consists of a plateau characterised by sand and lava fields, mountains, and glaciers, and many glacial rivers flow to the sea through the lowlands. Iceland is warmed by the Gulf Stream and has a temperate climate, despite a high latitude just outside the Arctic Circle. Its high latitude and marine influence keep summers chilly, with most of the archipelago having a polar climate.",
                            Flag = "https://restcountries.eu/data/isl.svg",
                            IsEUMember = true,
                            Name = "Iceland",
                            Population = 334300L
                        },
                        new
                        {
                            Id = new Guid("ef31333e-247a-439b-8f4e-3cc4a72f2417"),
                            Capital = "Dublin",
                            Currency = "Euro",
                            Description = "Ireland is an island in the North Atlantic. It is separated from Great Britain to its east by the North Channel, the Irish Sea, and St George's Channel. Ireland is the second-largest island of the British Isles, the third-largest in Europe, and the twentieth-largest on Earth.",
                            Flag = "https://restcountries.eu/data/irl.svg",
                            IsEUMember = true,
                            Name = "Ireland",
                            Population = 6378000L
                        },
                        new
                        {
                            Id = new Guid("f6937530-5cf9-42f7-863d-ecc69e3640d8"),
                            Capital = "Douglas",
                            Currency = "British pound",
                            Description = "The Isle of Man, also known as Mann, is a self-governing British Crown dependency situated in the Irish Sea between Great Britain and Ireland. The head of state, Queen Elizabeth II, holds the title of Lord of Mann and is represented by a lieutenant governor. The United Kingdom has responsibility for the island's defence.",
                            Flag = "https://restcountries.eu/data/imn.svg",
                            IsEUMember = true,
                            Name = "Isle of Man",
                            Population = 84497L
                        },
                        new
                        {
                            Id = new Guid("18820390-7dba-417b-beb3-7452d66c660c"),
                            Capital = "Rome",
                            Currency = "Euro",
                            Description = "Italy, officially the Italian Republic, is a European country consisting of a peninsula delimited by the Alps and surrounded by several islands. Italy is located in south-central Europe, and it is also considered a part of western Europe. A unitary parliamentary republic with its capital in Rome, the country covers a total area of 301,340 km2 (116,350 sq mi) and shares land borders with France, Switzerland, Austria, Slovenia, and the enclaved microstates of Vatican City and San Marino. Italy has a territorial exclave in Switzerland (Campione) and a maritime exclave in the Tunisian Sea (Lampedusa). With around 60 million inhabitants, Italy is the third-most populous member state of the European Union.",
                            Flag = "https://restcountries.eu/data/ita.svg",
                            IsEUMember = true,
                            Name = "Italy",
                            Population = 60665551L
                        },
                        new
                        {
                            Id = new Guid("30cf069e-55d0-4c36-86e4-f17e5f2f7a53"),
                            Capital = "Saint Helier",
                            Currency = "British pound",
                            Description = "Jersey, officially the Bailiwick of Jersey, is a British Crown dependency located near the coast of Normandy, France. It is the second-closest of the Channel Islands to France, after Alderney.",
                            Flag = "https://restcountries.eu/data/jey.svg",
                            IsEUMember = true,
                            Name = "Jersey",
                            Population = 100800L
                        },
                        new
                        {
                            Id = new Guid("53657db0-3841-4eb4-be41-e6f6d60fb24e"),
                            Capital = "Riga",
                            Currency = "Euro",
                            Description = "Latvia, officially known as the Republic of Latvia, is a country in the Baltic region of Northern Europe. Since its independence, Latvia has been referred to as one of the Baltic states. It is bordered by Estonia to the north, Lithuania to the south, Russia to the east, Belarus to the southeast, and shares a maritime border with Sweden to the west. Latvia has 1,957,200 inhabitants and a territory of 64,589 km2 (24,938 sq mi). The country has a temperate seasonal climate. The Baltic Sea moderates climate, although it has four distinct seasons and snowy winters.",
                            Flag = "https://restcountries.eu/data/lva.svg",
                            IsEUMember = true,
                            Name = "Latvia",
                            Population = 1961600L
                        },
                        new
                        {
                            Id = new Guid("e24a49d4-8816-4ee4-b74f-9548a8926870"),
                            Capital = "Vaduz",
                            Currency = "Swiss franc",
                            Description = "Liechtenstein, officially the Principality of Liechtenstein, is a German-speaking microstate situated in the Alps and in the southwest of Central Europe. The principality is a semi-constitutional monarchy headed by the Prince of Liechtenstein; the Prince's extensive powers are equivalent to those of a President in a semi-presidential system.",
                            Flag = "https://restcountries.eu/data/lie.svg",
                            IsEUMember = true,
                            Name = "Liechtenstein",
                            Population = 37623L
                        },
                        new
                        {
                            Id = new Guid("5b317c0d-84aa-40a1-a216-5e064427143e"),
                            Capital = "Vilnius",
                            Currency = "Euro",
                            Description = "Lithuania, officially the Republic of Lithuania, is a country in the Baltic region of Europe. Lithuania is considered to be one of the Baltic states. The country is situated along the southeastern shore of the Baltic Sea, to the east of Sweden and Denmark. It is bordered by Latvia to the north, Belarus to the east and south, Poland to the south, and Kaliningrad Oblast to the southwest. Lithuania has an estimated population of 2.8 million people as of 2019, and its capital and largest city is Vilnius. Other major cities are Kaunas and Klaipėda. Lithuanians are Baltic people. The official language, Lithuanian, is one of only two living languages in the Baltic branch of the Indo-European language family, the other being Latvian.",
                            Flag = "https://restcountries.eu/data/ltu.svg",
                            IsEUMember = true,
                            Name = "Lithuania",
                            Population = 2872294L
                        },
                        new
                        {
                            Id = new Guid("7a5c4e49-d890-480b-9ec5-df94fc8af915"),
                            Capital = "Luxembourg",
                            Currency = "Euro",
                            Description = "Luxembourg, officially the Grand Duchy of Luxembourg, is a landlocked country in western Europe. It is bordered by Belgium to the west and north, Germany to the east, and France to the south. Its capital, Luxembourg City, is one of the four official capitals of the European Union and the seat of the European Court of Justice, the highest judicial authority in the EU. Its culture, people, and languages are highly intertwined with its neighbours, making it essentially a mixture of French and German cultures, as evident by the nation's three official languages: French, German, and the national language of Luxembourgish. The repeated invasions by Germany, especially in World War II, resulted in the country's strong will for mediation between France and Germany and, among other things, led to the foundation of the European Union.",
                            Flag = "https://restcountries.eu/data/lux.svg",
                            IsEUMember = true,
                            Name = "Luxembourg",
                            Population = 576200L
                        },
                        new
                        {
                            Id = new Guid("1810f6bd-e00f-4d38-8214-5dbb3e8fa96b"),
                            Capital = "Skopje",
                            Currency = "Macedonian denar",
                            Description = @"Macedonia most commonly refers to:North Macedonia, a country in southeastern Europe, formerly known as the Republic of Macedonia
Macedonia, a kingdom in Greek antiquity
Macedonia (Greece), a traditional geographic region spanning three administrative divisions of northern Greece
Macedonia (region), a geographic and historical region that today includes parts of six Balkan countries ",
                            Flag = "https://restcountries.eu/data/mkd.svg",
                            IsEUMember = true,
                            Name = "Macedonia ",
                            Population = 2058539L
                        },
                        new
                        {
                            Id = new Guid("a4ffa786-57c6-46ef-88a8-d2c437103467"),
                            Capital = "Valletta",
                            Currency = "Euro",
                            Description = "Malta, officially known as the Republic of Malta, is a Southern European island country consisting of an archipelago in the Mediterranean Sea. It lies 80 km (50 mi) south of Italy, 284 km (176 mi) east of Tunisia, and 333 km (207 mi) north of Libya. With a population of about 475,000 over an area of 316 km2 (122 sq mi), Malta is the world's tenth smallest in area and fifth most densely populated sovereign country. Its capital is Valletta, which is the smallest national capital in the European Union by area at 0.8 km2 (0.31 sq mi). The official and national language is Maltese, which is descended from Sicilian Arabic that developed during the Emirate of Sicily, while English serves as the second official language.",
                            Flag = "https://restcountries.eu/data/mlt.svg",
                            IsEUMember = true,
                            Name = "Malta",
                            Population = 425384L
                        },
                        new
                        {
                            Id = new Guid("211557b7-3b91-4912-a7ee-83bea75048da"),
                            Capital = "Chișinău",
                            Currency = "Moldovan leu",
                            Description = "Moldova, officially the Republic of Moldova, is a landlocked country in Eastern Europe, bordered by Romania to the west and Ukraine to the north, east, and south. The capital city is Chișinău.",
                            Flag = "https://restcountries.eu/data/mda.svg",
                            IsEUMember = true,
                            Name = "Moldova ",
                            Population = 3553100L
                        },
                        new
                        {
                            Id = new Guid("61c50551-8ae5-4f7d-a1f3-fa84c5b74057"),
                            Capital = "Monaco",
                            Currency = "Euro",
                            Description = "Monaco, officially the Principality of Monaco, is a sovereign city-state, country, and microstate on the French Riviera in Western Europe. France borders the country on three sides while the other side borders the Mediterranean Sea. Monaco is about 15 km (9.3 mi) from the state border with Italy.",
                            Flag = "https://restcountries.eu/data/mco.svg",
                            IsEUMember = true,
                            Name = "Monaco",
                            Population = 38400L
                        },
                        new
                        {
                            Id = new Guid("cb35e222-4daa-40ff-af27-6c5c118454a0"),
                            Capital = "Podgorica",
                            Currency = "Euro",
                            Description = "Montenegro is a country of South and Southeast Europe on the coast of the Balkans. It borders Bosnia-Herzegovina to the northwest, Serbia to the northeast, Kosovo to the east, Albania to the southeast, the Adriatic Sea to the southwest, and Croatia to the west. Montenegro has an area of 13,812 square kilometres and a population of 620,079. Its capital, Podgorica, is one of the twenty-three municipalities in the country. Cetinje is designated as the Old Royal Capital.",
                            Flag = "https://restcountries.eu/data/mne.svg",
                            IsEUMember = true,
                            Name = "Montenegro",
                            Population = 621810L
                        },
                        new
                        {
                            Id = new Guid("59bc0649-d273-4570-bf75-b20c68c4227e"),
                            Capital = "Amsterdam",
                            Currency = "Euro",
                            Description = "The Netherlands, informally Holland, is a country in Northwestern Europe with some overseas territories in the Caribbean. In Europe, it consists of 12 provinces that border Germany to the east, Belgium to the south, and the North Sea to the northwest, with maritime borders in the North Sea with those countries and the United Kingdom. Together with the Caribbean Netherlands —Bonaire, Sint Eustatius and Saba—it forms a constituent country of the Kingdom of the Netherlands. The official language is Dutch and a secondary official language in the province of Friesland is West Frisian. In the north and east of the country, Low Saxon is also spoken, and in the southeast, Limburgish. In the Caribbean Netherlands English and Papiamento are recognised languages.",
                            Flag = "https://restcountries.eu/data/nld.svg",
                            IsEUMember = true,
                            Name = "Netherlands",
                            Population = 17019800L
                        },
                        new
                        {
                            Id = new Guid("84ea1c34-bc2f-4982-8099-6cc3739c32b2"),
                            Capital = "Oslo",
                            Currency = "Norwegian krone",
                            Description = "Norway, officially the Kingdom of Norway, is a Nordic country in Northwestern Europe whose territory comprises the western and northernmost portion of the Scandinavian Peninsula; the remote island of Jan Mayen and the archipelago of Svalbard are also part of the Kingdom of Norway. The sub-Antarctic Bouvet Island is a dependent territory and thus not considered part of the kingdom. Norway also lays claim to the Antarctic territories of Queen Maud Land and Peter I Island.",
                            Flag = "https://restcountries.eu/data/nor.svg",
                            IsEUMember = true,
                            Name = "Norway",
                            Population = 5223256L
                        },
                        new
                        {
                            Id = new Guid("9f347662-9845-4db2-a66e-50c640742aa9"),
                            Capital = "Warsaw",
                            Currency = "Polish złoty",
                            Description = "Poland, officially the Republic of Poland, is a country located in Central Europe. It is divided into 16 administrative subdivisions, covering an area of 312,696 square kilometres (120,733 sq mi), and has a largely temperate seasonal climate. With a population of nearly 38.5 million people, Poland is the fifth most populous member state of the European Union. Poland's capital and largest metropolis is Warsaw. Other major cities include Kraków, Łódź, Wrocław, Poznań, Gdańsk, and Szczecin.",
                            Flag = "https://restcountries.eu/data/pol.svg",
                            IsEUMember = true,
                            Name = "Poland",
                            Population = 38437239L
                        },
                        new
                        {
                            Id = new Guid("8a9631ef-15c0-438c-b310-67e68a6a38a4"),
                            Capital = "Lisbon",
                            Currency = "Euro",
                            Description = "Portugal, officially the Portuguese Republic, is a country located mostly on the Iberian Peninsula, in southwestern Europe. It is the westernmost sovereign state of mainland Europe, being bordered to the west and south by the Atlantic Ocean and to the north and east by Spain. Its territory also includes the Atlantic archipelagos of the Azores and Madeira, both autonomous regions with their own regional governments.",
                            Flag = "https://restcountries.eu/data/prt.svg",
                            IsEUMember = true,
                            Name = "Portugal",
                            Population = 10374822L
                        },
                        new
                        {
                            Id = new Guid("5de2b0fb-e875-45b4-ae89-ea8eec6f8a74"),
                            Capital = "Pristina",
                            Currency = "Euro",
                            Description = "Kosovo, officially the Republic of Kosovo, is a partially-recognized state in Southeast Europe, subject to a territorial dispute with the Republic of Serbia.",
                            Flag = "https://restcountries.eu/data/kos.svg",
                            IsEUMember = true,
                            Name = "Republic of Kosovo",
                            Population = 1733842L
                        },
                        new
                        {
                            Id = new Guid("fffbe257-30ac-4744-8685-6ec1d23d8af6"),
                            Capital = "Bucharest",
                            Currency = "Romanian leu",
                            Description = "Romania is a country located at the crossroads of Central, Eastern, and Southeastern Europe. It borders on the Black Sea to the southeast, and with Bulgaria to the south, Ukraine to the north, Hungary to the west, Serbia to the southwest, and Moldova to the east. It has a predominantly temperate-continental climate. With a total area of 238,397 square kilometres, Romania is the 12th-largest country in Europe and the 6th most populous member state of the European Union, having approximately 20 million inhabitants. Its capital and largest city is Bucharest. Other major urban areas include: Cluj-Napoca, Timișoara, Iași, Constanța, Craiova, Brașov, and Galați.",
                            Flag = "https://restcountries.eu/data/rou.svg",
                            IsEUMember = true,
                            Name = "Romania",
                            Population = 19861408L
                        },
                        new
                        {
                            Id = new Guid("187e550f-0b33-43a5-ac9b-63aab91e96fa"),
                            Capital = "Moscow",
                            Currency = "Russian ruble",
                            Description = "Russia, or the Russian Federation, is a transcontinental country located in Eastern Europe and Northern Asia. At 17,125,200 square kilometres (6,612,100 sq mi), it is, by a considerable margin, the largest country in the world by area, covering more than one-eighth of the Earth's inhabited land area, spanning eleven time zones, and bordering 16 sovereign nations. The territory of Russia extends from the Baltic Sea in the west to the Pacific Ocean in the east, and from the Arctic Ocean in the north to the Black Sea and the Caucasus in the south. With 146.7 million inhabitants living in the country's 85 federal subjects, Russia is the most populous nation in Europe and the ninth-most populous nation in the world. Russia's capital and largest city is Moscow; other major urban areas include Saint Petersburg, Novosibirsk, Yekaterinburg, Nizhny Novgorod, Kazan and Chelyabinsk.",
                            Flag = "https://restcountries.eu/data/rus.svg",
                            IsEUMember = true,
                            Name = "Russian Federation",
                            Population = 146599183L
                        },
                        new
                        {
                            Id = new Guid("2c02f802-2f62-46af-b004-97347da852f7"),
                            Capital = "City of San Marino",
                            Currency = "Euro",
                            Description = "San Marino, officially the Republic of San Marino, also known as the Most Serene Republic of San Marino, is an enclave microstate in Southern Europe, on the northeastern side of the Apennine Mountains, completely surrounded by Italy.",
                            Flag = "https://restcountries.eu/data/smr.svg",
                            IsEUMember = true,
                            Name = "San Marino",
                            Population = 33005L
                        },
                        new
                        {
                            Id = new Guid("21d80564-bf62-4d08-9b4a-7e3d7193fc90"),
                            Capital = "Belgrade",
                            Currency = "Serbian dinar",
                            Description = "Serbia, officially the Republic of Serbia, is a landlocked country situated at the crossroads of Central and Southeast Europe in the southern Pannonian Plain and the central Balkans. It borders Hungary to the north, Romania to the northeast, Bulgaria to the southeast, North Macedonia to the south, Croatia and Bosnia and Herzegovina to the west, and Montenegro to the southwest. The country claims a border with Albania through the disputed territory of Kosovo. Serbia's population numbers approximately seven million. Its capital, Belgrade, ranks among the largest citiеs in southeastern Europe.",
                            Flag = "https://restcountries.eu/data/srb.svg",
                            IsEUMember = true,
                            Name = "Serbia",
                            Population = 7076372L
                        },
                        new
                        {
                            Id = new Guid("c327f63e-3f35-407d-8e53-0fbdb8443ad1"),
                            Capital = "Bratislava",
                            Currency = "Euro",
                            Description = "Slovakia, officially the Slovak Republic, is a landlocked country in Central Europe. It is bordered by Poland to the north, Ukraine to the east, Hungary to the south, Austria to the southwest, and the Czech Republic to the northwest. Slovakia's territory spans about 49,000 square kilometres (19,000 sq mi) and is mostly mountainous. The population is over 5.6 million and consists mostly of Slovaks. The capital and largest city is Bratislava, and the second-largest city is Košice. The official language is Slovak.",
                            Flag = "https://restcountries.eu/data/svk.svg",
                            IsEUMember = true,
                            Name = "Slovakia",
                            Population = 5426252L
                        },
                        new
                        {
                            Id = new Guid("0bad868c-0468-4408-b750-483b1e62fd62"),
                            Capital = "Ljubljana",
                            Currency = "Euro",
                            Description = "Slovenia, officially the Republic of Slovenia, is a country located in Europe at the crossroads of main European cultural and trade routes. It is bordered by Italy to the west, Austria to the north, Hungary to the northeast, Croatia to the southeast, and the Adriatic Sea to the southwest. Slovenia covers 20,273 square kilometers (7,827 sq mi) and has a population of 2.084 million. One of the successor states of the former Yugoslavia, Slovenia is now a parliamentary republic and member nation of the European Union, United Nations, and NATO. The capital and largest city is Ljubljana.",
                            Flag = "https://restcountries.eu/data/svn.svg",
                            IsEUMember = true,
                            Name = "Slovenia",
                            Population = 2064188L
                        },
                        new
                        {
                            Id = new Guid("bfd26b5d-fa90-4787-a433-9fa7ae9ec798"),
                            Capital = "Madrid",
                            Currency = "Euro",
                            Description = "Spain, officially the Kingdom of Spain, is a country in Southwestern Europe with some pockets of Spanish territory across the Strait of Gibraltar and the Atlantic Ocean. Its continental European territory is situated on the Iberian Peninsula. Its territory also includes two archipelagoes: the Canary Islands off the coast of Africa, and the Balearic Islands in the Mediterranean Sea. The African enclaves of Ceuta, Melilla, and Peñón de Vélez de la Gomera make Spain the only European country to have a physical border with an African country (Morocco). Several small islands in the Alboran Sea are also part of Spanish territory. The country's mainland is bordered to the south and east by the Mediterranean Sea except for a small land boundary with Gibraltar; to the north and northeast by France, Andorra, and the Bay of Biscay; and to the west and northwest by Portugal and the Atlantic Ocean.",
                            Flag = "https://restcountries.eu/data/esp.svg",
                            IsEUMember = true,
                            Name = "Spain",
                            Population = 46438422L
                        },
                        new
                        {
                            Id = new Guid("c38ae48c-7f8a-4c88-b0ca-a0cae2cc58c0"),
                            Capital = "Longyearbyen",
                            Currency = "Norwegian krone",
                            Description = "Svalbard and Jan Mayen is a statistical designation defined by ISO 3166-1 for a collective grouping of two remote jurisdictions of Norway: Svalbard and Jan Mayen. While the two are combined for the purposes of the International Organization for Standardization (ISO) category, they are not administratively related. This has further resulted in the country code top-level domain .sj being issued for Svalbard and Jan Mayen, and ISO 3166-2:SJ. The United Nations Statistics Division also uses this code, but has named it Svalbard and Jan Mayen Islands.",
                            Flag = "https://restcountries.eu/data/sjm.svg",
                            IsEUMember = true,
                            Name = "Svalbard and Jan Mayen",
                            Population = 2562L
                        },
                        new
                        {
                            Id = new Guid("2caa560f-fbdc-44f1-a0ee-ca8f9361b041"),
                            Capital = "Stockholm",
                            Currency = "Swedish krona",
                            Description = "Sweden, officially the Kingdom of Sweden, is a Scandinavian country in Northern Europe. It borders Norway to the west and north and Finland to the east, and is connected to Denmark in the southwest by a bridge-tunnel across the Öresund Strait. At 450,295 square kilometres (173,860 sq mi), Sweden is the largest country in Northern Europe, the third-largest country in the European Union and the fifth largest country in Europe by area. The capital city is Stockholm. Sweden has a total population of 10.3 million of which 2.6 million have a foreign background. Persons who have foreign backgrounds are defined as persons who are foreign born, or born in Sweden with foreign born parents. It has a low population density of 22 inhabitants per square kilometre (57/sq mi) and the highest urban concentration is in the central and southern half of the country.",
                            Flag = "https://restcountries.eu/data/swe.svg",
                            IsEUMember = true,
                            Name = "Sweden",
                            Population = 9894888L
                        },
                        new
                        {
                            Id = new Guid("2ad01e91-902e-44ba-aba0-97de1eec1fa0"),
                            Capital = "Bern",
                            Currency = "Swiss franc",
                            Description = "Switzerland, officially the Swiss Confederation, is a country situated in the confluence of Western, Central, and Southern Europe. It is a federal republic composed of 26 cantons, with federal authorities seated in Bern. Switzerland is a landlocked country bordered by Italy to the south, France to the west, Germany to the north, and Austria and Liechtenstein to the east. It is geographically divided among the Swiss Plateau, the Alps, and the Jura, spanning a total area of 41,285 km2 (15,940 sq mi), and land area of 39,997 km2 (15,443 sq mi). While the Alps occupy the greater part of the territory, the Swiss population of approximately 8.5 million is concentrated mostly on the plateau, where the largest cities are located, among them the two global cities and economic centres of Zürich and Geneva.",
                            Flag = "https://restcountries.eu/data/che.svg",
                            IsEUMember = true,
                            Name = "Switzerland",
                            Population = 8341600L
                        },
                        new
                        {
                            Id = new Guid("156b0297-e113-49e8-9298-3cc5e36dddd5"),
                            Capital = "Kiev",
                            Currency = "Ukrainian hryvnia",
                            Description = "Ukraine is a country in Eastern Europe. It is bordered by Russia to the north-east; Belarus to the north; Poland, Slovakia and Hungary to the west; and Romania, Moldova, and the Black Sea to the south. Ukraine is currently in a territorial dispute with Russia over the Crimean Peninsula, which Russia annexed in 2014. Including the Crimean Peninsula, Ukraine has an area of 603,628 km2 (233,062 sq mi), making it the second-largest country in Europe after Russia, and the 46th-largest country in the world. Excluding Crimea, Ukraine has a population of about 42 million, making it the eighth or ninth-most populous country in Europe and the 32nd-most populous country in the world. Its capital and largest city is Kiev. Ukrainian is the official language and its alphabet is Cyrillic. The dominant religion in the country is Eastern Orthodoxy.",
                            Flag = "https://restcountries.eu/data/ukr.svg",
                            IsEUMember = true,
                            Name = "Ukraine",
                            Population = 42692393L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Capital = "London",
                            Currency = "British pound",
                            Description = "The United Kingdom of Great Britain and Northern Ireland, commonly known as the United Kingdom or Britain, is a sovereign country located off the north­western coast of the European mainland. The United Kingdom includes the island of Great Britain, the north­eastern part of the island of Ireland, and many smaller islands. Northern Ireland shares a land border with the Republic of Ireland. Otherwise, the United Kingdom is surrounded by the Atlantic Ocean, with the North Sea to the east, the English Channel to the south and the Celtic Sea to the southwest, giving it the 12th-longest coastline in the world. The Irish Sea separates Great Britain and Ireland. The total area of the United Kingdom is 94,000 square miles (240,000 km2).",
                            Flag = "https://restcountries.eu/data/gbr.svg",
                            IsEUMember = true,
                            Name = "United Kingdom",
                            Population = 65110000L
                        });
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.CountryFavourites", b =>
                {
                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FavouriteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CountryId", "FavouriteId");

                    b.HasIndex("FavouriteId");

                    b.ToTable("CountryFavourites");
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.CountryPhotoMemories", b =>
                {
                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CountryId", "MemoryId");

                    b.HasIndex("MemoryId");

                    b.ToTable("CountryPhotoMemories");
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.CountryWishlists", b =>
                {
                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CountryId", "WishlistId");

                    b.HasIndex("WishlistId");

                    b.ToTable("CountryWishlists");
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.Favourite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.PhotoMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.SpotifyPlaylist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaylistId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CountrySpotifyPlaylist");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44d3168f-b63d-4bcf-a59f-56793b826e84"),
                            CountryId = new Guid("476bc0eb-e17d-4967-b86f-1e09682c81b5"),
                            PlaylistId = "2CusBjVWAtRWy0L5BfmikW"
                        },
                        new
                        {
                            Id = new Guid("6d475074-cac7-4fb1-a108-895b46875989"),
                            CountryId = new Guid("7d4ceeaa-d15d-4775-9227-627be6acbd00"),
                            PlaylistId = "7l0CFkcQuUzGolpc36QMIC"
                        },
                        new
                        {
                            Id = new Guid("e6ca924e-f55f-4a96-a76d-6f3dcce41e7e"),
                            CountryId = new Guid("6ff85e22-61d5-4ba5-a805-276358c3dff9"),
                            PlaylistId = "53lWeMXMoJ2wWUS1nYnBgl"
                        },
                        new
                        {
                            Id = new Guid("fbe598af-7e19-42f1-87f7-6f25ed936e73"),
                            CountryId = new Guid("8576e077-183f-4e29-8a6d-5e5a49a021c0"),
                            PlaylistId = "5Gu9Cbjqk2MAXo1yY09lCk"
                        },
                        new
                        {
                            Id = new Guid("6234416e-57e0-44e8-b2f6-b6c475d45f0c"),
                            CountryId = new Guid("4963724f-4004-44e7-98dd-3e102042eb62"),
                            PlaylistId = "50AOO2iX1bfP12JDe2cSAN"
                        },
                        new
                        {
                            Id = new Guid("28c0ab47-85c4-491a-a486-5a41508fc2b0"),
                            CountryId = new Guid("f9266fa7-d009-44c1-bc84-bef8e948caa2"),
                            PlaylistId = "6DpX8j1kTO55ZazVWIUJ9H"
                        },
                        new
                        {
                            Id = new Guid("1164f30d-584a-45db-a4d1-28f04e9bdd25"),
                            CountryId = new Guid("691703c7-9a52-42fe-a87f-5e7115e28f30"),
                            PlaylistId = "0LexRqlNAFHzIG3upGcA0S"
                        },
                        new
                        {
                            Id = new Guid("590b019e-d8f1-486a-ac82-158b9e4a8fa1"),
                            CountryId = new Guid("da3b2494-96a0-4003-81a2-81e434524285"),
                            PlaylistId = "0T73gC6LcZuhHfxuhTUSd5"
                        },
                        new
                        {
                            Id = new Guid("8dd643a3-2c03-48ce-97da-ae03a76c53c3"),
                            CountryId = new Guid("bb6f1d45-0219-45c5-bb30-34dd9b0b341f"),
                            PlaylistId = "253ARKQpYyLw3VYbIiy2zn"
                        },
                        new
                        {
                            Id = new Guid("103d6ba9-7789-4286-8253-be41846fe841"),
                            CountryId = new Guid("df396ddc-06e1-4794-8ae8-4c6e294a3675"),
                            PlaylistId = "7nUxZrzOz1FS67LYqsjdIv"
                        },
                        new
                        {
                            Id = new Guid("79d22122-dfbb-4466-8c90-8a390ac9e61e"),
                            CountryId = new Guid("e5970e72-bd18-4996-a595-ddc658cd8d53"),
                            PlaylistId = "1ObBKzabSHf6WD4VZI8fJU"
                        },
                        new
                        {
                            Id = new Guid("21ec3215-5fbc-4935-9e52-6d3c4f5e24f8"),
                            CountryId = new Guid("9d609d89-8e7a-4218-a71f-9c27180119f1"),
                            PlaylistId = "5EC6uJxihNWkD5ZlYXKpL5"
                        },
                        new
                        {
                            Id = new Guid("9716fdb1-40b9-4fad-be16-5578b14ac89d"),
                            CountryId = new Guid("73d00cef-69e3-40ae-b756-df15767e89dd"),
                            PlaylistId = "2CusBjVWAtRWy0L5BfmikW"
                        },
                        new
                        {
                            Id = new Guid("d6dc0194-22e2-4c83-99a3-dc2a11997d21"),
                            CountryId = new Guid("af1fd177-7df3-4dd1-b449-068b0d701459"),
                            PlaylistId = "0QgtRvswo2Ugn0B1MTHQkW"
                        },
                        new
                        {
                            Id = new Guid("6f801db4-eafe-4fb0-bc7c-9a8be212450c"),
                            CountryId = new Guid("37dd0095-5300-499f-a5c8-320cf28142ba"),
                            PlaylistId = "7Cdk1T18F4mJKNPJxmP8o3"
                        },
                        new
                        {
                            Id = new Guid("de8ba7eb-d52d-40ce-9173-ffbaae7f2e74"),
                            CountryId = new Guid("ed2f71f4-66f7-4597-a631-059a5967b659"),
                            PlaylistId = "30EHPgCW4KRgOR4VumFHfs"
                        },
                        new
                        {
                            Id = new Guid("037cb815-1781-49bf-ae17-7b66703a04af"),
                            CountryId = new Guid("700e77da-10c0-4571-9d41-ad79383f2573"),
                            PlaylistId = "1s8ckUBY7ZZjrJMPZ4BtOj"
                        },
                        new
                        {
                            Id = new Guid("d0126626-98a2-4d40-85fa-fed4fdc2cfc7"),
                            CountryId = new Guid("be40d8c3-b922-4ac5-8d49-27f63b3983cb"),
                            PlaylistId = "7LsbwkqPWuIVjM8OmqJyJh"
                        },
                        new
                        {
                            Id = new Guid("22a9a0fd-2160-48ea-9c6e-dfd8ebf3d50b"),
                            CountryId = new Guid("7b50048f-c613-4db5-858c-8b2a0ced2027"),
                            PlaylistId = "2dvjKJLYeizywy2NQiKlVO"
                        },
                        new
                        {
                            Id = new Guid("77b4fac0-1cb2-41b7-b0ee-5dbb9ac40476"),
                            CountryId = new Guid("ef31333e-247a-439b-8f4e-3cc4a72f2417"),
                            PlaylistId = "2zesk6vpZhemqH9FbZKZnq"
                        },
                        new
                        {
                            Id = new Guid("d8ec1175-ec6a-439d-bff4-549ef59ed112"),
                            CountryId = new Guid("f6937530-5cf9-42f7-863d-ecc69e3640d8"),
                            PlaylistId = "2zesk6vpZhemqH9FbZKZnq"
                        },
                        new
                        {
                            Id = new Guid("15c725dc-d03c-48d3-8464-827f266cad11"),
                            CountryId = new Guid("18820390-7dba-417b-beb3-7452d66c660c"),
                            PlaylistId = "0ylcsCmX0r03zT9yISmFWp"
                        },
                        new
                        {
                            Id = new Guid("be6a3f27-4b92-4270-b837-a5ca415a02ce"),
                            CountryId = new Guid("5b317c0d-84aa-40a1-a216-5e064427143e"),
                            PlaylistId = "12CfDHYf2nkZANtS9f9Vew"
                        },
                        new
                        {
                            Id = new Guid("3518cd9c-03b4-49b0-a75c-6c602c9d6fd1"),
                            CountryId = new Guid("7a5c4e49-d890-480b-9ec5-df94fc8af915"),
                            PlaylistId = "09TxUze3BuYVNvMY6d418n"
                        },
                        new
                        {
                            Id = new Guid("4a3d79a2-7687-424f-a948-23d43f2a6d7e"),
                            CountryId = new Guid("1810f6bd-e00f-4d38-8214-5dbb3e8fa96b"),
                            PlaylistId = "6wk61XRax6dMvX3WClLYbH"
                        },
                        new
                        {
                            Id = new Guid("12bed140-d999-4512-9b4c-539a771f583c"),
                            CountryId = new Guid("211557b7-3b91-4912-a7ee-83bea75048da"),
                            PlaylistId = "3ZzdoANeDnNgpPDN8BdL59"
                        },
                        new
                        {
                            Id = new Guid("e427617d-e413-4bce-ab66-97280377376d"),
                            CountryId = new Guid("61c50551-8ae5-4f7d-a1f3-fa84c5b74057"),
                            PlaylistId = "3gl4XsDZjDEhP6ENWG0SSm"
                        },
                        new
                        {
                            Id = new Guid("3933ba8f-ecde-414f-bc97-72c69464cc86"),
                            CountryId = new Guid("cb35e222-4daa-40ff-af27-6c5c118454a0"),
                            PlaylistId = "4AJvqhZvRE796GP9RYNrYc"
                        },
                        new
                        {
                            Id = new Guid("40540d79-40b6-4f9b-aaa5-2da634940776"),
                            CountryId = new Guid("59bc0649-d273-4570-bf75-b20c68c4227e"),
                            PlaylistId = "0FRAi3HnfdGT5Gn69MvYlT"
                        },
                        new
                        {
                            Id = new Guid("043c56ea-217c-4d5f-ae03-68f976f1a111"),
                            CountryId = new Guid("84ea1c34-bc2f-4982-8099-6cc3739c32b2"),
                            PlaylistId = "6KgYE0tontk4mf54YQfXXS"
                        },
                        new
                        {
                            Id = new Guid("2b74bcfe-841d-45c3-a1ee-a9a623324f67"),
                            CountryId = new Guid("9f347662-9845-4db2-a66e-50c640742aa9"),
                            PlaylistId = "29XoM5S9Yc6Heflhp9fIoC"
                        },
                        new
                        {
                            Id = new Guid("ac38761d-b28f-4789-b5a7-d06ff3c698f9"),
                            CountryId = new Guid("8a9631ef-15c0-438c-b310-67e68a6a38a4"),
                            PlaylistId = "5fpIpFlXUplr5Uy1J1qHnO"
                        },
                        new
                        {
                            Id = new Guid("eefdc9e6-892d-460b-afa9-51f080455130"),
                            CountryId = new Guid("5de2b0fb-e875-45b4-ae89-ea8eec6f8a74"),
                            PlaylistId = "47dFbcLDn04CX7UorU8Iq8"
                        },
                        new
                        {
                            Id = new Guid("4a8062fb-241d-45a9-beba-55eca86af3c4"),
                            CountryId = new Guid("fffbe257-30ac-4744-8685-6ec1d23d8af6"),
                            PlaylistId = "0g5twCr1C6oituq3La2Div"
                        },
                        new
                        {
                            Id = new Guid("97c62250-b236-496a-aed4-c6873ed3947b"),
                            CountryId = new Guid("187e550f-0b33-43a5-ac9b-63aab91e96fa"),
                            PlaylistId = "6d3Zwzras2ghumJvnlIqsI"
                        },
                        new
                        {
                            Id = new Guid("0598e0a8-4069-41d8-a703-95ceeea92061"),
                            CountryId = new Guid("2c02f802-2f62-46af-b004-97347da852f7"),
                            PlaylistId = "7BSjWFXtpiJxdvzMSBl7Sq"
                        },
                        new
                        {
                            Id = new Guid("8e49cf3f-3a28-440c-beec-875f9c89f60f"),
                            CountryId = new Guid("21d80564-bf62-4d08-9b4a-7e3d7193fc90"),
                            PlaylistId = "1nN2hfHzcXNsVeGAwXev3s"
                        },
                        new
                        {
                            Id = new Guid("f8c39315-68cb-410c-9661-acfd2953ef05"),
                            CountryId = new Guid("c327f63e-3f35-407d-8e53-0fbdb8443ad1"),
                            PlaylistId = "65nrfnJcCxTLsyyjf8WCXe"
                        },
                        new
                        {
                            Id = new Guid("79aff82f-b698-4f8a-a2e4-2678c070f986"),
                            CountryId = new Guid("bfd26b5d-fa90-4787-a433-9fa7ae9ec798"),
                            PlaylistId = "1irDloS9VCX40czYAS2klR"
                        },
                        new
                        {
                            Id = new Guid("c9161afc-7eb6-45cc-b983-cdb809535c3e"),
                            CountryId = new Guid("c38ae48c-7f8a-4c88-b0ca-a0cae2cc58c0"),
                            PlaylistId = "6KgYE0tontk4mf54YQfXXS"
                        },
                        new
                        {
                            Id = new Guid("8f7f55be-df8b-4387-9560-0b0478d3947c"),
                            CountryId = new Guid("2caa560f-fbdc-44f1-a0ee-ca8f9361b041"),
                            PlaylistId = "3BeBGfOciz2pHhmMYGF7Qq"
                        },
                        new
                        {
                            Id = new Guid("df60e5c4-5cbd-46ba-b82b-eeb1d7c118a7"),
                            CountryId = new Guid("2ad01e91-902e-44ba-aba0-97de1eec1fa0"),
                            PlaylistId = "7KCEnXSAo8e4aHkC3Barql"
                        },
                        new
                        {
                            Id = new Guid("458991ce-4f08-4a25-bb30-df18bd1f7175"),
                            CountryId = new Guid("156b0297-e113-49e8-9298-3cc5e36dddd5"),
                            PlaylistId = "5S1GVxkVbKXxoTV8DwBKGi"
                        },
                        new
                        {
                            Id = new Guid("861b24d5-eaf0-4302-9ff6-aea03a67269e"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PlaylistId = "1y7E5GXSac77FzesM2ASjx"
                        });
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSpotifyDj")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5311214-564f-4824-ba65-b57042349e49"),
                            BirthDate = new DateTime(1998, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gaspard.lammertyn@student.howest.be",
                            FirstName = "Gaspard",
                            IsSpotifyDj = false,
                            LastName = "Lammertyn",
                            Nationality = "Belgium",
                            Password = "AQAAAAEAACcQAAAAECB838lOiltn3vC+LWa6l225mVrXcpdTYd8iDSIN30nsSQj8zH/YmrUrXstOwn8cKA==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BirthDate = new DateTime(1998, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test.test@student.howest.be",
                            FirstName = "test",
                            IsSpotifyDj = true,
                            LastName = "test",
                            Nationality = "Belgium",
                            Password = "AQAAAAEAACcQAAAAEMdvl3OdsfGmQIMMfwZfEsJ+ddcQ9brPFH9autxAHpKOYvCAgCDa4li1+4O5Er1pAQ==",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.CountryFavourites", b =>
                {
                    b.HasOne("WorldExplorerEurope.API.Domain.Models.Country", "Country")
                        .WithMany("Favourites")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldExplorerEurope.API.Domain.Models.Favourite", "Favourite")
                        .WithMany("Favourites")
                        .HasForeignKey("FavouriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.CountryPhotoMemories", b =>
                {
                    b.HasOne("WorldExplorerEurope.API.Domain.Models.Country", "Country")
                        .WithMany("Memories")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldExplorerEurope.API.Domain.Models.PhotoMemory", "Memory")
                        .WithMany("Memories")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorldExplorerEurope.API.Domain.Models.CountryWishlists", b =>
                {
                    b.HasOne("WorldExplorerEurope.API.Domain.Models.Country", "Country")
                        .WithMany("CountryWishlists")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldExplorerEurope.API.Domain.Models.Wishlist", "Wishlist")
                        .WithMany("Wishlists")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
